VMap.nmap("<leader>sn", require("dap").continue)
VMap.nmap("<leader>sa", require("dap").toggle_breakpoint)
VMap.nmap("<leader>sj", require("dap").step_over)
VMap.nmap("<leader>sk", require("dap").step_back)
VMap.nmap("<leader>sl", require("dap").step_into)
VMap.nmap("<leader>sh", require("dap").step_out)
VMap.nmap("<leader>ssb", require("dap").clear_breakpoints)
VMap.nmap("<leader>sc", require("dap").run_to_cursor)
VMap.nmap("<leader>sr", function()
  require("dap.repl").toggle({}, "vsplit")
end)
VMap.nmap("<leader>st", require("dapui").toggle)
VMap.nmap("<leader>se", require("dapui").eval)
VMap.nmap("<leader>sb", require("telescope").extensions.dap.list_breakpoints)
VMap.nmap("<leader>sf", require("telescope").extensions.dap.frames)
