VMap.tmap("<C-l>", "<cmd>wincmd l<CR>")
VMap.tmap("<C-h>", "<cmd>wincmd h<CR>")
VMap.tmap("<C-j>", "<cmd>wincmd j<CR>")
VMap.tmap("<C-k>", "<cmd>wincmd k<CR>")
VMap.tmap("<C-F11>", "<cmd>ToggleTerm<CR>")
VMap.map("<C-F11>", "<cmd>ToggleTerm<CR>")
